# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Hariprasanth Venkataramachetty
title: Full Stack Engineer | @PayPal Ex:Cisco, Intuit.
email: hariprasanth89@gmail.com
website: https://hariprasanth89.github.io/hariprasanth

# Dark Mode (true/false/never)
darkmode: false

# Social links
# twitter_username: facespics
github_username:  hariprasanth89
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
# instagram_username: jameswgrant
linkedin_username: hariprasanth-venkatarama-chetty-19193723
# xing_username: jekyll
# pinterest_username: jekyll
# youtube_username: globalmtb
# googleplus_username: +jekyll
# orcid_username: 0000-0000-0000-0000

# Additional icon links
additional_links:
- title: My homepage
  icon: fas fa-globe
  url: https://hariprasanth89.github.io/hariprasanth
- title: Email Me
  icon: fas fa-envelope
  url: mailto:hariprasanth89@gmail.com
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me
about_profile_image: images/profile_hari.jpg
about_content: | # this will include new lines to allow paragraphs
  Welcome to my personal website! <br><br>
  I am **Hariprasanth Venkataramachetty**, a **Full Stack Software Engineer** with over **13 years of experience** in **backend and frontend development, cloud platforms, and DevOps practices**. Skilled in **Java, Spring Boot, Node.js, React, and cloud services (AWS, GCP, Azure)**, with a strong focus on **scalable application design, API development, and secure authentication (OAuth2, SSO, API keys)**.<br><br>
  Worked with **leading clients such as PayPal, Cisco, and Intuit**, contributing to **large-scale system development, CI/CD pipeline automation (Jenkins, Harness), and infrastructure migration**. Experienced in **microservices architecture, database management (SQL/NoSQL), and Agile/Scrum methodologies**, with a proven ability to **collaborate across cross-functional teams** and deliver high-quality, secure software solutions.

content:
  # - title: Projects # Title for the section
  #   layout: list # Type of content section (list/text)
  #   content:
  #     - layout: top-middle
  #       title: Super awesome project
  #       link: github.com/sproogen
  #       # link_text: Project Website
  #       additional_links:
  #         - title:  sproogen/modern-resume-theme
  #           icon: fab fa-github
  #           url: github.com/sproogen/modern-resume-theme
  #         # - title:  Github page for project (eg. sproogen/modern-resume-theme)
  #         #   icon: fab fa-github
  #         #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)
  #       quote: >
  #         This is probably one of the greatest apps ever created, if you don't agree you're probably wrong.
  #       description: | # this will include new lines to allow paragraphs
  #         I started this project as a way if learning <mark>React</mark> and it has since grown into a fully fledged app. I have learned many skills through this and been I'm very proud of having this in my portfolio. If you don't have a project as awesome as this I would advise you make one.

  - title: Experience # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: PayPal
        link: https://www.paypal.com And https://www.venmo.com
        sub_title: Full Stack Engineer
        caption: October 2024 - Present
        quote: >
          Contributed to PayPal and Venmo engineering initiatives, focusing on full-stack development, CI/CD automation, and secure API integrations.
        description: | # this will include new lines to allow paragraphs
            Collaborated with designers, QA, and business teams to deliver projects using Agile/Scrum methodologies. 
            Developed and deployed Spring Boot applications on AWS Beanstalk, integrating REST and SOAP APIs for scalable services. 
            Optimized microservices through caching, asynchronous fetching, and secure authentication with OAuth2 and SSO. 
            Ensured secure API integrations within ECM and payment platforms by implementing OAuth2 and API keys. 

            Contributed to CI/CD processes with Jenkins and Harness, including IAM roles and secure VPC design for reliable deployments. 
            Wrote, reviewed, and tested Java and Node.js code while resolving defects during integration phases. 
            Automated builds and dependency management using Jenkins, Harness, and Git pipelines. 
            Led SDLC initiatives with strong emphasis on Agile practices such as sprint planning, backlog grooming, and retrospectives.

      - layout: left
        title: Cisco
        link: https://www.cisco.com
        sub_title: Full Stack Engineer
        caption: March 2024 - September 2024
        quote: >
          Contributed to Cisco’s Estimates, Quoting, Ordering, and Subscriptions/Renewals modules, driving backend development and system integrations.
        description: |
          Worked extensively on core modules, delivering backend and integration workflows with Spring Boot and Hibernate. 
          Utilized advanced Hibernate features such as inheritance, lazy loading, dirty checking, optimistic locking, and transaction management for efficient data handling. 
          Followed Agile practices including pair programming, TDD, and daily Scrum meetings to ensure iterative and collaborative delivery. 

          Built backend services across multiple layers (Entity/Model, DAO/Repository, Service, Controller, Business, Persistence) and created RESTful APIs validated via Postman for client and third-party integrations. 
          Developed frontend interfaces using React Class Components, managing state effectively to support business workflows. 
          Maintained unit testing frameworks with JUnit, writing comprehensive test cases for stability and functionality. 

          Tracked project tasks using JIRA for transparency and progress updates, while managing Git repositories with branching strategies, pull requests, and merges. 
          Actively contributed to all phases of the SDLC, including sprint planning, backlog grooming, and retrospectives, ensuring alignment with Agile methodologies.
    
      - layout: left
        title: Worldscape Inc.
        link: https://www.worldscapeinc.com
        sub_title: Full Stack Engineer
        caption: September 2023 - February 2024
        quote: >
          Developed and maintained scalable web applications with React and Node.js, improving user experience and platform performance.
        description: |
          Built and maintained web applications using JavaScript, React, and Node.js, ensuring responsive and efficient functionality. 
          Collaborated closely with designers to deliver intuitive, user-friendly interfaces that enhanced customer experience. 
          Integrated APIs across multiple platforms to extend application features and improve system interoperability. 

          Proactively troubleshot and resolved software defects to maintain performance and reliability. 
          Eliminated system bottlenecks and crashes through optimization, significantly improving overall user experience.
    
      - layout: left
        title: Intuit.
        link: https://www.intuit.com
        sub_title: Full Stack Engineer
        caption: February 2022 - August 2023
        quote: >
          Designed and developed full-stack applications for Intuit using Spring Boot, Hibernate, and React, ensuring scalable and maintainable software solutions.
        description: |
          Developed backend services using Spring Boot, implementing multiple layers including Entity/Model, DAO/Repository, Controller, Service, Business, and Persistence. 
          Designed and created database schemas, integrating them with the application using Hibernate (ORM) for efficient object-relational mapping. 
          Implemented batch processing with Spring Batch to extract and load data from CSV/Excel files into database tables. 

          Created and validated RESTful APIs for data operations, leveraging Postman for endpoint testing. 
          Built frontend applications using React Class Components, effectively managing state for smooth user interactions. 
          Wrote comprehensive unit tests with JUnit to ensure code quality and reliability. 

          Tracked project progress with JIRA, managing tasks transparently within Agile workflows. 
          Maintained version control using Git, overseeing repositories, branching strategies, pull requests, and merges. 
          Actively participated in all phases of the SDLC, contributing to sprint planning, backlog grooming, daily stand-ups, and retrospectives.
    
      - layout: left
        title: Trie Coders Pvt Ltd.
        link: http://www.triecoders.com/
        sub_title: Sr. Software Engineer, 
        caption: Dec 2017 - Nov 2021
        quote: >
          Experienced in backend development, microservices, and API integration for banking and financial applications.
        description: |
          Worked on a banking app enabling users to manage accounts and transactions. Implemented backend services for updating user personal information and developed multiple modules. Optimized microservices using Lombok, participated in agile sprints and daily scrums, and contributed to code reviews and meetings. Managed JSON request-response flows between UI and API teams, and deployed Java-based services on AWS Beanstalk for scalability and reliability.

  - title: Education & Recognitions # Title for the section
    layout: text # Changing format for better UI presentation
    content: |
    
      ## **Sathyabama University**
      **Years:** 2007 - 2011.  
      **Degree:** BE CSE - Bachulor of Engineering.  
      **Major:** Computer Science and Engineering.
      **Institution:** [Sathyabama University](https://sathyabama.ac.in)
    
      🎓 **Bachelor of Engineering (B.E.) in Computer Science and Engineering**
         Graduated with a strong foundation in computer science principles and software engineering practices, developing skills in software development, problem-solving, and system design
    
      ---

# Footer
footer_show_references: false
footer_content: |
    Copyright 2025 Hariprasanth Venkataramachetty. All rights reserved. | 📧 [hariprasanth89@gmail.com](mailto:hariprasanth89@gmail.com)
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
